20:31:56.866 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:31:58.871 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$e7c48107: null
20:31:58.883 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$34549df8: null
20:31:58.902 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$34549df8: null
20:31:58.952 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:33:00.144 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:33:02.631 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$e7df613f: null
20:33:02.640 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$346f7e30: null
20:33:02.657 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$346f7e30: null
20:33:02.704 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:33:16.818 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:33:19.327 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$ed63fb16: null
20:33:19.339 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$39f41807: null
20:33:19.361 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$39f41807: null
20:33:19.408 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:34:13.343 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_13]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_13]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_13]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_13]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.2.jar:2.12.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_13]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_13]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_13]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_13]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:113) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.2.jar:2.12.2]
20:34:13.352 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_13]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_13]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_13]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_13]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252) [surefire-junit4-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141) [surefire-junit4-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112) [surefire-junit4-2.12.2.jar:2.12.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_13]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_13]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_13]
	at java.lang.reflect.Method.invoke(Method.java:601) ~[na:1.7.0_13]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189) [surefire-api-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:113) [surefire-booter-2.12.2.jar:2.12.2]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75) [surefire-booter-2.12.2.jar:2.12.2]
20:34:14.741 [main] ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$9238d1a7: null
20:34:14.751 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$dec8ee98: null
20:34:14.769 [main] ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$dec8ee98: null
20:41:15.553 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:41:19.184 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$a1f2f772: null
20:41:19.199 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$ee831463: null
20:41:19.224 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$ee831463: null
20:41:19.273 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:44:39.831 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:44:43.662 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$30d682bf: null
20:44:43.701 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$7d669fb0: null
20:44:43.754 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$7d669fb0: null
20:44:43.804 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:44:48.518 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException: null
	at com.teoware.refapp.web.consumer.error.ErrorHandlerTest.testHandleServiceException(ErrorHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
20:44:51.487 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException$$EnhancerByMockitoWithCGLIB$$fa4edf5d: null
20:44:51.509 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$46defc4e: null
20:44:51.548 ERROR c.t.r.w.c.e.ErrorHandler - Service error occured
com.teoware.refapp.service.ServiceException$$EnhancerByMockitoWithCGLIB$$46defc4e: null
20:44:51.598 ERROR c.t.r.w.c.e.ValidationHandler - Validation error occured
com.teoware.refapp.service.validation.ValidationException: null
	at com.teoware.refapp.web.consumer.error.ValidationHandlerTest.testHandleValidationException(ValidationHandlerTest.java:12) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.6.0_39]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39) ~[na:1.6.0_39]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_39]
	at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_39]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:44) [junit-4.9.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15) [junit-4.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:41) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20) [junit-4.9.jar:na]
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:22) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69) [junit-4.9.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222) [junit-4.9.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:292) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:157) [junit-4.9.jar:na]
	at org.junit.runner.JUnitCore.run(JUnitCore.java:136) [junit-4.9.jar:na]
	at org.infinitest.testrunner.JUnit4Runner.runTest(JUnit4Runner.java:66) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.runTest(TestRunnerProcess.java:64) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.writeTestResultToOutputStream(TestRunnerProcess.java:106) [infinitest.jar:na]
	at org.infinitest.testrunner.TestRunnerProcess.main(TestRunnerProcess.java:83) [infinitest.jar:na]
